### ISSUE TITLE
Add flag to lowercase the locale?

### ISSUE THREAD

**Issue by tboerger** [simia-tech/caddy-locale#3]
I have written a Caddyfile like this:

```
:80 {
  root /srv/www

  locale en-US zh-CN zh-TW pt-BR nl-NL {
    detect header
  }

  redir 301 {
    if {path} not_match ^/{>Detected-Locale}/
    / /{>Detected-Locale}/
  }

  header / Vary "Accept-Language"
}
```

Generally it works good, but my content is structured like `/zh-cn/foo`, `/en-us/foo`, `/pt-br/foo` and so on, but the above Caddyfile results in a 404 error. Can we have another attribute for `locale` to downcase the locale?

**Comment by phifty** [comment]
Hi Thomas,

Thanks for the feedback. Sounds definitely like a valid problem. I could also imagine to add an ‘ignore_case‘ flag to the ‘locale‘ section. Would this solve your problem?

**Comment by tboerger** [comment]
I think that can help already.

**Comment by phifty** [comment]
Thinking of it again, I imagine the flag not necessary at all. All cases that I can think of would work with an case-insensitive match. So that is implemented now. Hope your problem is fixed.

Cheers

**Comment by tboerger** [comment]
That will solve my problem, thanks!
