### ISSUE TITLE
Submit plugin to new Caddy website

### ISSUE THREAD

**Issue by mholt** [simia-tech/caddy-locale#4]
Hey Philipp, did you get my email about adding this plugin to the new Caddy website? Is there anything I can do to help get it added there before next Thursday?

**Comment by phifty** [comment]
Unfortunately, I'm on vacation and won't be able to work on it before the end of the month.

**Comment by mholt** [comment]
Enjoy your vacation. :) Feel free to add it whenever you get back.

**Comment by uberswe** [comment]
Would be awesome if it could be added, our ansible scripts no longer works due to this

**Comment by woubuc** [comment]
@phifty any update on this? Will the plugin be added to the website?

**Comment by phifty** [comment]
Excuse the late response. It's added now.

**Comment by mholt** [comment]
Yay! I'll tweet this.
