### ISSUE TITLE
Publish on the Caddy website

### ISSUE THREAD

**Issue by elegaanz** [simia-tech/caddy-locale#5]
Hello! I don't know if this plugin is still maintained, but if it is it would be nice to publish to the Caddy website, so that it can be used for real. Thank you. :slightly_smiling_face:

**Comment by phifty** [comment]
Hi, last time I checked, the plugin is still published to the Caddy website. Just add it as a plugin.

**Comment by elegaanz** [comment]
Oh, I missed it in the list. Sorry.
