### ISSUE TITLE
Build issues on caddyserver.com

### ISSUE THREAD

**Issue by magikstm** [simia-tech/caddy-locale#6]
I believe the issue could be corrected by using a valid release version tag in the form `v0.1.0` or `v1.0.0`.

Ref: https://caddy.community/t/plugins-having-build-issues-as-of-05-06-2019/5817

**Comment by phifty** [comment]
I've added the tag. Please counter-check

**Comment by schmkr** [comment]
I was just able to download a custom build with this plugin from the website. 👍
